FROM python:3.7

WORKDIR /bp-directory-back

RUN apt-get update && apt-get install -y \
        vim \
        telnet net-tools \
        postgresql postgresql-client postgresql-contrib

COPY . /bp-directory-back

RUN pip install --no-cache-dir \
        -r /block-producers-directory-back/dev.txt \
        -r /block-producers-directory-back/project.txt \
        -r /block-producers-directory-back/tests.txt
