FROM python:3.7

WORKDIR /block-producers-directory-back

RUN apt-get update && apt-get install -y \
        vim \
        telnet net-tools \
        postgresql postgresql-client postgresql-contrib

COPY . /block-producers-directory-back

RUN pip install --no-cache-dir -r /block-producers-directory-back/requirements.txt
