# Generated by Django 2.2.3 on 2019-07-22 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockProducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('website_url', models.URLField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('short_description', models.CharField(max_length=100)),
                ('full_description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('medium_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('reddit_url', models.URLField(blank=True)),
                ('slack_url', models.URLField(blank=True)),
                ('wikipedia_url', models.URLField(blank=True)),
                ('steemit_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
