# Generated by Django 2.2.3 on 2019-07-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_producer', '0003_block_producer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockproducer',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockproducer',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockproducer',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockproducer',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockproducer',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blockproducer',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockproducer',
            name='medium_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockproducer',
            name='reddit_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockproducer',
            name='slack_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockproducer',
            name='steemit_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockproducer',
            name='telegram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockproducer',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockproducer',
            name='wikipedia_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
