# Generated by Django 2.2.4 on 2019-08-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_producer', '0003_block_producer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockproducer',
            name='logo_url',
            field=models.URLField(blank=True, default='https://block-producers-directory.s3-us-west-2.amazonaws.com/bps/logos/default-block-producer-logotype.png'),
        ),
    ]
