# Generated by Django 2.2.4 on 2019-08-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_producer', '0004_add_default_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockproducer',
            name='status',
            field=models.CharField(choices=[('moderation', 'moderation'), ('declined', 'declined'), ('active', 'active')], default='moderation', max_length=10),
        ),
    ]
