# Generated by Django 2.2.4 on 2019-08-27 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block_producer', '0005_add_status_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockproducer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
