# Generated by Django 2.2.4 on 2019-09-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_producer', '0005_add_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockproducer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
