# Generated by Django 2.2.4 on 2019-08-27 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block_producer', '0006_user_one_to_one_bp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockproducerlike',
            name='block_producer',
        ),
        migrations.RemoveField(
            model_name='blockproducerlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlockProducerComment',
        ),
        migrations.DeleteModel(
            name='BlockProducerLike',
        ),
    ]
