# Generated by Django 2.2.5 on 2019-09-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_producer', '0006_add_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockproducer',
            name='status_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='blockproducer',
            name='full_description',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
