# Generated by Django 2.2.6 on 2019-10-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_producer', '0007_add_status_description_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockproducer',
            name='logo_url',
            field=models.URLField(blank=True, default='https://block-producers-directory.s3-us-west-2.amazonaws.com/bps/logos/default-block-producer-logotype.png', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blockproducer',
            name='status_description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blockproducercomment',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
