# Generated by Django 2.2.3 on 2019-07-22 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_override_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('avatar_url', models.URLField(blank=True)),
                ('additional_information', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('medium_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('steemit_url', models.URLField(blank=True)),
            ],
        ),
    ]
