# Generated by Django 2.2.3 on 2019-07-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_add_profile_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
