# Generated by Django 2.2.4 on 2019-08-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_create_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, default='https://block-producers-directory.s3-us-west-2.amazonaws.com/user/avatars/default-user-logotype.png'),
        ),
    ]
