# Generated by Django 2.2.4 on 2019-08-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_add_default_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
