# Generated by Django 2.2.6 on 2019-10-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_add_is_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='additional_information',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, default='https://block-producers-directory.s3-us-west-2.amazonaws.com/users/avatars/default-user-logotype.png', max_length=1000),
        ),
    ]
